### ISSUE TITLE
Taking long time to publish event to Event hub after 1 hour of idle time

### ISSUE THREAD

**Issue by prashant-gudodagi-by** [Azure/azure-event-hubs-for-kafka#108]
Description
===========
Connected to Azure Event Hub, In a normal working scenario with no idle time, the events gets published to event hub within milliseconds, but if there is an idle time of 1 hour, the first event sent after idle time takes 30 secs.

Framework: Spring
Parameters used for Producer:
KEY_SERIALIZER_CLASS_CONFIG
VALUE_SERIALIZER_CLASS_CONFIG
COMPRESSION_TYPE_CONFIG

other properties will be considered default..

How to reproduce
================
Connect to Azure Event hub, using the above mentioned config values (org.apache.kafka.clients.producer.ProducerConfig).

After connecting send couple of messages.(1st request takes time to publish and all other subsequent events gets published in fraction)
get idle time of 1 hour.
Now publish a new message, it takes almost 30 Secs.

Has it worked previously?
=========================
<Is this a first attempt at getting the sample application to run, or has it worked in the past?>

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed or where adequate information has not been provided.

Please provide the relevant information for the following items:
 - [ ] SDK (include version info): `<REPLACE with e.g., kafka-python/Java SDK/confluent-kafka-dotnet with version info>`
 - [ ] Sample you're having trouble with: `<REPLACE with e.g., Java quickstart>`
 - [x] If using Apache Kafka Java clients or a framework that uses Apache Kafka Java clients, version: `<REPLACE with e.g., 1.1.0>`
 - [ ] Kafka client configuration: `<REPLACE with e.g., auto.reset.offset=earliest, ..>` (*do not include your connection string or SAS Key*)
 - [ ] Namespace and EventHub/topic name
 - [ ] Consumer or producer failure `<REPLACE with e.g., Consumer failure>`
 - [ ] Timestamps *in UTC* `<REPLACE with e.g., Nov 7 2018 - 17:15:01 UTC>`
 - [ ] group.id or client.id `<REPLACE with e.g., group.id=cg-name>`
 - [ ] Logs provided (with debug-level logging enabled if possible, e.g. log4j.rootLogger=DEBUG) or exception call stack
 - [ ] Standalone repro `<REPLACE with e.g., Willing/able to send scenario to repro issue>`
 - [ ] Operating system: `<REPLACE with e.g., Ubuntu 16.04.5 (x64) LTS>`
 - [ ] Critical issue

If this is a question on basic functionality, please verify the following:
 - [ ] Port 9093 should not be blocked by firewall ("broker cannot be found" errors)
 - [ ] Pinging FQDN should return cluster DNS resolution (e.g. `$ ping namespace.servicebus.windows.net` returns ~ `ns-eh2-prod-am3-516.cloudapp.net [13.69.64.0]`)
 - [ ] Namespace should be either Standard or Dedicated tier, not Basic (TopicAuthorization errors)

**Comment by arerlend** [comment]
Hey @prashant-gudodagi-by can you try setting all of the configuration found in the config doc?  Setting max idle timeout for config should help you. 

https://github.com/Azure/azure-event-hubs-for-kafka/blob/master/CONFIGURATION.md

**Comment by arerlend** [comment]
@prashant-gudodagi-by any update?

**Comment by dandev486** [comment]
@arerlend, could you provide me some guidance about the suggestion of setting `connections.max.idle.ms`? Experiencing the same scenario, low latency with high message volume and high latency with low message volume (eg.: 1 message for each 15 minutes). In our tests we diagnosed that the problem is currently neither on producing nor commiting, so it leaves the publishing time as the most probable reason.

How does setting the `connections.max.idle.ms` would affect a singleton producer instance (created in such way to reduce the number of instantiations on high demand scenarios)? Considering that Azure EventHub closes connections after this configurable amount of time, should we also periodically recreate the producer instance in order to prevent sending to dead connections?

Thanks in advance!
