### ISSUE TITLE
org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms

### ISSUE THREAD

**Issue by vs199vishal** [Azure/azure-event-hubs-for-kafka#32]
I have a kafka enable event namespace. Request is coming to my event.
Do topic creation is auto ?? I have manually created test topic.

**Comment by vs199vishal** [comment]
find the below ref:
<img width="497" alt="ku" src="https://user-images.githubusercontent.com/45196132/51076283-93274d80-16bc-11e9-92e8-f3e5ac99d58b.png">
<img width="960" alt="k" src="https://user-images.githubusercontent.com/45196132/51076285-94587a80-16bc-11e9-8072-615f52a7d4fa.png">

**Comment by vs199vishal** [comment]
why message is not coming to my topic. getting timeout exception

**Comment by arerlend** [comment]
@vs199vishal please fill out the issue template below so that we can help you out as best as possible.

Description
===========
<Describe the issue here>

How to reproduce
================
<How to reproduce the issue, or remove section if not relevant>

Has it worked previously?
=========================
<Is this a first attempt at getting the sample application to run, or has it worked in the past?>

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:
 
 - [ ] Verified that port 9093 is not blocked by firewall
 - [ ] Verified the namespace is either Standard or Dedicated tier (i.e. it is not Basic tier, which isn't supported)
 - [ ] Sample you're having trouble with: `<REPLACE with e.g., Java quickstart>`
 - [x] Apache Kafka version: `<REPLACE with e.g., 1.1.0>`
 - [ ] Kafka client configuration: `<REPLACE with e.g., auto.reset.offset=earliest, ..>` (*do not include your connection string or SAS Key*)
 - [ ] Namespace and EventHub/topic name
 - [ ] Consumer or producer failure `<REPLACE with e.g., Consumer failure>`
 - [ ] If consumer, partition ID, group ID `<REPLACE with e.g., partitionID=3, groupID=consumer-group>`
 - [ ] Timestamp in UTC `<REPLACE wtih e.g., Nov 7 2018 - 17:15:01 UTC> 
 - [ ] Client ID `<REPLACE with e.g., clientID=kafka-client>
 - [ ] Provide all logs (with debugging enabled if possible) or exception call stack
 - [ ] Standalone repro <REPLACE with e.g., Willing/able to send scenario to repro issue>
 - [ ] Operating system: `<REPLACE with e.g., Ubuntu 16.04.5 (x64) LTS>`
 - [ ] Critical issue

**Comment by basilhariri** [comment]
@vs199vishal we need more info from you before we can help. are you following the Java quickstart?

Can you post your producer’s configuration file (with your connection string removed)?

**Comment by vs199vishal** [comment]
servicebus.windows.net was missing in eventhub namespace.
Thank you for all your support and time.

**Comment by Styazoua** [comment]
Hello,
I'm having the same problem like @vs199vishal
I also followd all the steps to configure.
servicebus.windows.net in namespace is set.
Connectionstring copied from azure.
Event Hub ist kafka enabled.

**Comment by coder-PengWenHao** [comment]
how to solve ?

**Comment by mattlevan** [comment]
@coder-PengWenHao Check to make sure you're using the name of your Event Hub for the `TOPIC` variable in `TestProducer.java`. That solved it for me.

**Comment by ben-garza** [comment]
A customer is having this same issue:

at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: org.apache.kafka.common.errors.TimeoutException: Topic mediastate_topic not present in metadata after 60000 ms.

Most recent timestamp :
Sep 12, 2021 @ 20:53:46.818 (EST)

Subscription ID -be7e4bde-9994-4ee1-bdfd-f3f96fe826fe
EH host :pre-prod-cc-abt-eventhub-ns.servicebus.windows.net

 Verified that port 9093 is not blocked by firewall -- Port is open
 Verified the namespace is either Standard or Dedicated tier (i.e. it is not Basic tier, which isn't supported) -- Standard
 Kafka client configuration: 

PRODUCER
Property | Value Set in our config | Recommended Values | Permitted Range
-- | -- | -- | --
max.request.size | 1000000 | 1000000 | < 1046528
retries | 10000 | > 0 |  
request.timeout.ms | 30000 | 30000 … 60000 | > 20000
metadata.max.idle.ms | 180000 | 180000 | > 5000
linger.ms | 5 | > 0 |  
delivery.timeout.ms | 300050000 |   |  
compression.type | none | none |  
metadata.max.age.ms | 180000 | ~ 180000 | < 240000
connections.max.idle.ms | 180000 | 180000 | < 240000

CONSUMER
Property | Value Set in our config | Recommended Values | Permitted Range
-- | -- | -- | --
heartbeat.interval.ms | 3000 (default) | 3000 |  
session.timeout.ms | 300000 | 30000 | 6000 … 300000
max.poll.interval.ms | 480000 | 300000 (default) | > session.timeout.ms
metadata.max.age.ms | 180000 | ~ 180000 | < 240000
connections.max.idle.ms | 180000 | 180000 | < 240000

 Sample you're having trouble with: Custom app
 Apache Kafka version: 1.1
 Namespace and EventHub/topic name : pre-prod-cc-abt-eventhub-ns.servicebus.windows.net / mediastate_topic
 Consumer or producer failure Producer
 If consumer, partition ID, group ID <REPLACE with e.g., partitionID=3, groupID=consumer-group>
 Timestamp in UTC: `Sep 13, 2021 @ 00:53:46.818 (UTC)
 Client ID `<REPLACE with e.g., clientID=kafka-client>
 Provide all logs (with debugging enabled if possible) or exception call stack:  Not available in PROD (Running in AKS)
 Standalone repro <REPLACE with e.g., Willing/able to send scenario to repro issue>
 Operating system: <REPLACE with e.g., Ubuntu 16.04.5 (x64) LTS>
 Critical issue - Yes
