### ISSUE TITLE
[Feature clarification] Can we achieve routing based ingestion to Azure data explorer using the Kafka enabled event hub

### ISSUE THREAD

**Issue by prmoh** [Azure/azure-event-hubs-for-kafka#59]
Description
===========

We are working as part of a PoC where we wanted to ship application logs to Azure Data Explorer via Kafka enabled event hub. 
We can create a event data source in the azure data explorer and give hard coded ingestion mapping to map to the column names to that of the incoming json object. 
There is another option to create a data source which will take routing information from the event. If the event originated from .net/java code we can mark the event.proporties to appropriate routing of the events to the destination tables in azure data explorer. 
As we are using a Kafka based log shipper [ file beat ], we don't have any control over the event creation. 
We wanted to know if we can have some key value in the payload which event hub can read and route the payload based on that ? 

How to reproduce
================
Feature ask

**Comment by romangusiev** [comment]
+1

**Comment by basilhariri** [comment]
This isn't possible. Event Hubs never looks at the payload as anything other than a byte array. 

If you need to route the payload in some specific way, the way to accomplish that is to send it to a specific topic or partition in the same way that you would with Kafka. I assume you have _some_ control over the event creation because you can decide where to send it (which Kafka cluster/topic or Event Hub), is there any way you can leverage that?
