### ISSUE TITLE
Does it support mirroring messages from Event Hubs to Kafka?

### ISSUE THREAD

**Issue by zuojihong** [Azure/azure-event-hubs-for-kafka#77]
Description
===========
In some scenarios, telemetry messages are first routed from IoT Hub to Event Hubs through messaging routing. And the telemetry messages need to be sent to Kafka cluster for data analytics. So, we need to support mirroring messages from EH to Kafka in reverse way. Is this scenario supported?

**Comment by arerlend** [comment]
@zuojihong right now Mirrormaker is your best bet.  You can consume via Kafka clients from the Event Hub backing your IoT hub... just get that EH connection string and follow the instructions here - https://github.com/Azure/azure-event-hubs-for-kafka/tree/master/tutorials/mirror-maker.

Closing for now, but feel free to keep commenting if you have more questions.

**Comment by arerlend** [comment]
Took a quick look at the tutorial and I understand why you may be confused.

You can run Mirrormaker in both directions.  Just swap your source and destination configurations - that way you will consume from Event Hub and produce to your Kafka cluster.

By the way, it depends on how you are running your data analytics workload, but have you considered just running your analytics workload on directly on top of Event Hub instead of Kafka?

**Comment by zuojihong** [comment]
@arerlend Good to know that, thanks! The reason for raising the question is that some customers need to fan out messages from IoT Hub to Event Hubs and then they're seeking for a convenient way to transfer the messages from Event Hubs to Kafka cluster for analytics.
