### ISSUE TITLE
Zookeeper crushing my application

### ISSUE THREAD

**Issue by Houcem-abdellatif** [Azure/azure-event-hubs-for-kafka#96]
When running my application without Azure Event Hub, it works.
The moment I switch to using Azure Event hub my application crushes.
After a bit of research I found that Zookeeper is currently not supported with azure Event Hub however Zookeeper is essential and my application won't start without it. 

Screen shot of when I use Event Hub with Kafka and Zookeeper: 
![accretioError](https://user-images.githubusercontent.com/51375451/76086337-32d82700-5fb4-11ea-9bf9-b532539751c0.png)

**Comment by basilhariri** [comment]
Hi @Houcem-abdellatif, could you fill out the issue template? There is a lot of info we could use to help you debug that is missing. Are you running one of the samples?

Is zookeeper essential to your application specifically, or is it only necessary in that it supports the kafka cluster you're connecting to? Zookeeper is not a part of Event Hubs for Kafka, so any attempts to use Zookeeper directly will fail.

**Comment by Houcem-abdellatif** [comment]
Hello, Zookeeper is necessary to supports the kafka cluster, I am looking to integrate Zookeeper with Azure Event Hubs for Kafka. 
The issue template didn't have information that i can provide.

**Comment by basilhariri** [comment]
EventHubs for Kafka is almost always used as a replacement for Kafka+Zookeeper. You connect your clients to the EventHubs service as if it were a Kafka cluster and leave all the managing  (including anything managed by Zookeeper) to us. If you are using EventHubs for Kafka, you shouldn't need to support a Kafka cluster anymore.

I understand the template is quite extensive, but there must be some information you can provide us. We need to know more about your application to help. Please fill out the template to the best of your ability - I've attached it below for your convenience.

Description
===========
<Describe the issue here>

How to reproduce
================
<How to reproduce the issue, or remove section if not relevant>

Has it worked previously?
=========================
<Is this a first attempt at getting the sample application to run, or has it worked in the past?>

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed or where adequate information has not been provided.

Please provide the relevant information for the following items:
 - [ ] SDK (include version info): `<REPLACE with e.g., kafka-python/Java SDK/confluent-kafka-dotnet with version info>`
 - [ ] Sample you're having trouble with: `<REPLACE with e.g., Java quickstart>`
 - [x] If using Apache Kafka Java clients or a framework that uses Apache Kafka Java clients, version: `<REPLACE with e.g., 1.1.0>`
 - [ ] Kafka client configuration: `<REPLACE with e.g., auto.reset.offset=earliest, ..>` (*do not include your connection string or SAS Key*)
 - [ ] Namespace and EventHub/topic name
 - [ ] Consumer or producer failure `<REPLACE with e.g., Consumer failure>`
 - [ ] Timestamps *in UTC* `<REPLACE with e.g., Nov 7 2018 - 17:15:01 UTC>`
 - [ ] group.id or client.id `<REPLACE with e.g., group.id=cg-name>`
 - [ ] Logs provided (with debug-level logging enabled if possible, e.g. log4j.rootLogger=DEBUG) or exception call stack
 - [ ] Standalone repro `<REPLACE with e.g., Willing/able to send scenario to repro issue>`
 - [ ] Operating system: `<REPLACE with e.g., Ubuntu 16.04.5 (x64) LTS>`
 - [ ] Critical issue

If this is a question on basic functionality, please verify the following:
 - [ ] Port 9093 should not be blocked by firewall ("broker cannot be found" errors)
 - [ ] Pinging FQDN shoudl return cluster DNS resolution (e.g. `$ ping namespace.servicebus.windows.net` returns ~ `ns-eh2-prod-am3-516.cloudapp.net [13.69.64.0]`)
 - [ ] Namespace should be either Standard or Dedicated tier, not Basic (TopicAuthorization errors)

**Comment by arerlend** [comment]
We do not have a dependency on Zookeeper.  Are you using a tool/client that requires connecting to Zookeeper?

**Comment by Houcem-abdellatif** [comment]
**Has it worked previously?**
It works normally, the moment i integrate Kafka for Event Hub it crushes. 
**Checklist** :
SDK (include version info): Java 1.8
I use spring-cloud-stream-binder-kafka 
Maven version : 3.0.0
Operating System : Ubuntu 16.04
It's a standalone repo

**Comment by arerlend** [comment]
Event Hubs does not use Zookeeper and we do not expose an endpoint that provides Zookeeper functionality.  EH is only compatible with Kafka clients v1.0+, and consumers from v0.9+ do not require a Zookeeper connection.
